### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by xin-huang** [bvernot/freezing-archer#2]
Hi Ben,

I am trying to calculate S* with the individual HG00096 (chr21) from 1000 genomes.

The command I used is 
```
python ./bin/windowed_calculations.py \ 
    --s-star \ 
    -vcfz ./test_data/HG00096.vcf.gz \ 
    -indf ./test_data/sample_pop_mapping_file.txt \ 
    -ptable ./program_data/archaic_match_table_files.neand_table.fields_8-10.12-.gz.db \
    -target-pops TEST \
    -ref-pops YRI \
    --archaic-vcf ./program_data/filtered_vcfs_neand_mpi_minimal_filters/chr21.neand_filtered.vcf.gz \
    -p 10 \
    -ancbsg ./program_data/chimp.bsg \
    -winlen  50000 \
    -winstep 10000 \
    -table-query mh len mapped \
    -tag-ids bigpop \
    -tags TEST \
    -range 0 10000000
```

The `sample_pop_mapping_file.txt` I used is
```
sample  pop     super_pop       gender
HG00096 test    TEST    .
```

But I got this error
```
Traceback (most recent call last):
  File "./bin/windowed_calculations.py", line 315, in <module>
    run_window_analysis(chrom, winstart, winend, snps, opts)
  File "/proj/admixlab/introgression-benchmark/tools/freezing-archer/bin/s_star_fns.py", line 398, in run_window_analysis
    (match_pvals2, match_pct2, ref_nones) = calc_local_match_pval(chrom, winstart, winend, snps, opts)
  File "/proj/admixlab/introgression-benchmark/tools/freezing-archer/bin/s_star_fns.py", line 377, in calc_local_match_pval
    pvals[ind*2] = (ps_1 if ps_1 > 0 else 1) / opts.num_reference / 2
```
I cannot find `opts.num_reference` from the command line options. Could you please help me to fix this issue?
Thank you.

**Comment by xin-huang** [comment]
If I added `-no-pavlues`, then I can run the above command successfully.

**Comment by xin-huang** [comment]
Looks like option `-ref-inds` should be used to specify individuals as the reference panel
